AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template that sends AWS CodeCommit data to Splunk HEC.
Resources:
  WebhooktoHEC:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: s3://codecommit-lambda-splunk/function.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /webhook-to-hec
            Method: ANY
